### ISSUE TITLE
Invalid configurations - kenzer.conf wiki

### ISSUE THREAD

**Issue by RDMDR** [ARPSyndicate/kenzer#11]
Hey,

Could you please provide further information to configure kenzer.conf, please ?
I keep getting "[!] invalid configurations" and I'm not sure on which parameters I'm doing wrong.

Thanks,
RDMDR

**Comment by g147** [comment]
We recently released a new version & maybe that fixes your issue.
In case it does not, can you share redacted configuration?

**Comment by g147** [comment]
Refer this one -
https://github.com/ARPSyndicate/kenzer/issues/4

**Comment by RDMDR** [comment]
Thanks for the link. It helped me to configure it but I have another error.

Here is my conf file : 
`[env]
home=/root/
greynoise={greynoise-community-api-token}
xsshunter={xss-hunter-endpoint}

[kenzerdb]
path=/root/kenzer/kenzerdb/directory/
token={github-personal-access-token}
user={github-user}
repo={github-repository}

[kenzer]
email=kenzer-bot@xxxxxxxx.zulipchat.com
path=/root/kenzer/
key=xxxxxxxxxxxxxxxxxxxxxxxx
site=https://xxxxxxxx.zulipchat.com
uploads=False
subscribe=False
logging=False
splitting=True
syncing=False`

In the first place, I don't know what 'greynoise' and 'xss-hunter' are use for.
And why I should add github infos in the [kenzerdb] part.
-> Are thos parameters mandatory ?


Here is the last stack trace I'm getting 

`[/root/kenzer] $./run.sh 
KENZER[3.47] by ARPSyndicate
automated web assets enumeration & scanning
[*] training chatterbot
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 434, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 831, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 563, in checkout
    rec = pool._do_get()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 1355, in _do_get
    return self._create_connection()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 379, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 508, in __init__
    self.__connect(first_connect_check=True)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 710, in __connect
    connection = pool._invoke_creator(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/kenzer/kenzer.py", line 1381, in <module>
    main()
  File "/root/kenzer/kenzer.py", line 1375, in main
    bot = Kenzer()
  File "/root/kenzer/kenzer.py", line 75, in __init__
    self.chatbot = ChatBot("Kenzer")
  File "/home/user/.local/lib/python3.9/site-packages/chatterbot/chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/chatterbot/utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/chatterbot/storage/sql_storage.py", line 46, in __init__
    if not self.engine.dialect.has_table(self.engine, 'Statement'):
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1356, in has_table
    info = self._get_table_pragma(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1799, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2143, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2192, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2231, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1528, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 434, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 831, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 563, in checkout
    rec = pool._do_get()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 1355, in _do_get
    return self._create_connection()
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 379, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 508, in __init__
    self.__connect(first_connect_check=True)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/pool.py", line 710, in __connect
    connection = pool._invoke_creator(self)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
`

I keep on looking, ty

**Comment by g147** [comment]
Hey! 

Greynoise is for calculating the reputation score for targets.
(https://github.com/ARPSyndicate/domrep, https://www.greynoise.io/)

XSSHunter is for fuzzing for Blind XSS utilizing DalFox
(https://xsshunter.com/, https://github.com/hahwul/dalfox)

And yeah the path for KenzerDB is mandatory but the credentials aren't.
It is basically a database that Kenzer utilizes to stay synchronized with other instances.
In case you don't want your recon data to be uploaded on GitHub then it isn't necessary to fill those credentials.
Just let them be blank - ""
(https://github.com/ARPSyndicate/kenzerdb)

The exception seems to be invoked by Chatterbot due to permission or some other OS related issue.
You can comment the chatterbot training part in the source code & it should run fine.

**Comment by RDMDR** [comment]
Hey, thanks a lot for your complete answer !

IT'S WORKING !!! 👍 :
[*] KENZER is online
[*] 36 modules up & running
